name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Make vcan0 bus for unit tests
      run: |
        sudo ip link add dev vcan0 type vcan
        sudo ip link set vcan0 up

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 sphinx sphinx-rtd-theme setuptools wheel
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics

    - name: Test with Python's unittest
      run: python -m unittest

    - name: Test building pypi package
      run: python setup.py sdist bdist_wheel

    - name: Test building sphinx docs
      run: make -C docs html
